# Generated by Django 5.1.2 on 2025-02-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression_name', models.CharField(max_length=50)),
                ('confidence_per', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpressionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=50)),
                ('duration', models.FloatField()),
                ('confidence', models.FloatField()),
                ('video_name', models.CharField(max_length=100)),
            ],
        ),
    ]
