# Generated by Django 5.1.6 on 2025-02-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfidenceScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=100, unique=True)),
                ("expression_confidence", models.FloatField()),
                ("eye_movement_confidence", models.FloatField()),
                ("speech_confidence", models.FloatField()),
                ("hand_gesture_confidence", models.FloatField()),
                ("overall_confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ExpressionResult",
        ),
    ]
