# Generated by Django 5.1.6 on 2025-02-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_confidencescore_delete_expressionresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("percentage", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Eyes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("side", models.CharField(max_length=50)),
                ("percentage", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="HandsExpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("move", models.CharField(max_length=100, unique=True)),
                ("percentage", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Speech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=255, unique=True)),
                ("percentage", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="ConfidenceScore",
        ),
        migrations.DeleteModel(
            name="ExpressionData",
        ),
    ]
