# Generated by Django 5.1.6 on 2025-10-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_expression_eyes_handsexpression_speech_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("role", models.CharField(default="candidate", max_length=20)),
            ],
        ),
    ]
