# Generated by Django 5.1.6 on 2025-10-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("video_path", models.CharField(max_length=500)),
                ("overall_confidence", models.FloatField()),
                ("detailed_results", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.user"
                    ),
                ),
            ],
        ),
    ]
