# Generated by Django 5.1.6 on 2025-10-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_analysisresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="expression_confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="eye_movement_confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="hand_gesture_confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="speech_confidence",
            field=models.FloatField(default=0.0),
        ),
    ]
