# Generated by Django 5.2.8 on 2025-11-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_analysisresult_expression_confidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresult",
            name="speech_details",
            field=models.TextField(default="[]"),
        ),
    ]
