# Generated by Django 5.1.2 on 2025-10-11 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression_confidence', models.FloatField()),
                ('eye_movement_confidence', models.FloatField()),
                ('speech_confidence', models.FloatField()),
                ('hand_gesture_confidence', models.FloatField()),
                ('overall_confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
