# Generated by Django 5.1.2 on 2025-10-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_candidaterecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterecord',
            name='video_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
