# Generated by Django 5.1.2 on 2025-10-11 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_candidaterecord_video_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterecord',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
